#!/bin/bash

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
else
  controlfolder="/roms/ports/PortMaster"
fi

source $controlfolder/control.txt

get_controls

GAMEDIR="/$directory/ports/Godot"
if [[ $LOWRES == 'Y' ]]; then
  swidth="320"
  sheight="480"
  sscale="1"
elif [[ "$(cat /sys/firmware/devicetree/base/model)" == "Anbernic RG552" ]] || [[ -e "/dev/input/by-path/platform-singleadc-joypad-event-joystick" ]]; then
  swidth="1920"
  sheight="1080"
  sscale="3"
elif [[ -e "/dev/input/by-path/platform-odroidgo3-joypad-event-joystick" ]]; then
  swidth="854"
  sheight="480"
  sscale="3"
else
  swidth="640"
  sheight="480"
  sscale="3"
fi

RES="${swidth}x${sheight}"

if [ -z $1 ]; then
  game="${GAMEDIR}/games/${GAMENAME}"
else    
  game="${1}"    
fi
 
$ESUDO chmod 666 /dev/uinput
cd $GAMEDIR/bin/
# Uncomment one of the below lines to change the version of FRT being used
# make sure only one is uncommented, or you can run into issues. By default FRT 2 for Godot 3.4.4 is used.
FRT="frt_200_344_arm32v7.bin"
# Uncomment the below line to enable FRT 2 for 32bit Godot 2.1.6 
#frt_200_216_arm32v7.bin -f --resolution $RES --main-pack "$PATH"
#frt_200_344_arm64v8.bin
# Uncomment the below line to enable FRT 2 for 64bit Godot 2.1.6 
#frt_200_216_arm64v8.bin -f --resolution $RES --main-pack "$PATH"

# Uncomment the below line to enable FRT 2 for 32bit Godot 3.4.4 
#frt_200_344_arm32v7.bin -f --resolution $RES --main-pack "$PATH"
$GPTOKEYB $FRT -c "$GAMEDIR/bin/godot.gptk" &
#This is the default option using FRT 2 for 64bit Godot 3.4.4
#$ESUDO ./oga_controls ./$FRT $param_device &
SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig" &
./$FRT --video-driver GLES3 -f --resolution $RES --main-pack $game 2>&1 | tee $GAMEDIR/log.txt
$ESUDO kill -9 $(pidof gptokeyb)
$ESUDO systemctl restart oga_events &
printf "\033c" >> /dev/tty1
